# Generated by Django 5.2.7 on 2025-10-27 14:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="sample",
            name="is_published",
            field=models.BooleanField(default=False, verbose_name="published"),
        ),
        migrations.AlterField(
            model_name="sample",
            name="likes_count",
            field=models.IntegerField(default=0, verbose_name="likes count"),
        ),
        migrations.AlterField(
            model_name="sample",
            name="views_count",
            field=models.IntegerField(default=0, verbose_name="views count"),
        ),
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(fields=["slug"], name="sample_samp_slug_05a638_idx"),
        ),
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(fields=["-created_at"], name="sample_samp_created_7dce9c_idx"),
        ),
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(
                fields=["is_published", "-published_at"], name="sample_samp_is_publ_960eec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sample",
            index=models.Index(
                fields=["author", "-created_at"], name="sample_samp_author__72e655_idx"
            ),
        ),
    ]
