# Generated by Django 5.2.7 on 2025-10-28 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sample", "0002_alter_sample_is_published_alter_sample_likes_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="About",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("context", models.CharField(max_length=255, verbose_name="context")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="created at")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="updated at")),
            ],
            options={
                "verbose_name": "about",
                "verbose_name_plural": "abouts",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["id"], name="sample_abou_id_c8d15a_idx"),
                    models.Index(fields=["-created_at"], name="sample_abou_created_114baf_idx"),
                ],
            },
        ),
    ]
